kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: lfs158 # access to the specified namespace
  name: pod-reader # name of the role to create
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
