apiVersion: v1
kind: Pod # Pod object type
metadata:
  name: share-pod # Object name
  labels:
    app: share-pod
spec: # state of the pod (PodSpec), single pod running nginx:1.15.11 image from DockerHub
  volumes:
  - name: host-volume
    hostPath:
      path: /home/docker/pod-volume
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: host-volume
  - name: debian
    image: debian
    volumeMounts:
    - mountPath: /host-vol
      name: host-volume
    command: ["/bin/sh", "-c", "echo Introduction to kubernetes > /host-vol/index.html; sleep 3600"]
