apiVersion: apps/v1 # API Endpoint which we want to connect to
kind: Deployment # Object type (can be Pod, Replicaset, Namespace, Service, etc.)
metadata: # Object basic information
  name: nginx-deployment
  labels:
    app: nginx
spec: # Marks the beginning of the desired state of the deployment object
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: # Start of pods template
      containers:
      - name: nginx
        image: nginx:1.15.11 # image speec
        ports:
        - containerPort: 80
