apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: <<base64 encoded certificate>>
  usages:
  - digital signature
  - key encipherment
  - client auth
